# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - APIAggregator

on:
  push:
    branches:
      - Release/v1.0
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://dockerinstance.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ec913c9c5d9c4b508c9f674c03480624 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c48d8cbf2044401b8b9859cc23f894ec }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: dockerinstance.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ec913c9c5d9c4b508c9f674c03480624 }}/Apos.API.Aggregator:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'APIAggregator'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_cd1fba8edb90471f9ce40dd93d276a45 }}
        images: 'dockerinstance.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ec913c9c5d9c4b508c9f674c03480624 }}/Apos.API.Aggregator:${{ github.sha }}'